[build]
  base    = ""
  command = "npm run build"
  publish = "build"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install && npm run build"
  publish = "build"